[meta]
save_dir = "experiments"
description = "This is a description of FullSubNet experiment."
seed = 0  # set random seed for random, numpy, pytorch-gpu and pytorch-cpu
keep_reproducibility = false  # see https://pytorch.org/docs/stable/notes/randomness.html
use_amp = false  # use automatic mixed precision, it will benefits Tensor Core-enabled GPU (e.g. Volta, Turing, Ampere). 2-3X speedup。

[acoustic]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256

[train_dataset]
path = "dataset.DNS_INTERSPEECH_train.Dataset"
[train_dataset.args]
clean_dataset = "/media/administrator/736be68f-3ad2-4ea3-8ebf-c2e3983b05c9/Data/DNS-Challenge/datasets/clean"
clean_dataset_limit = false
clean_dataset_offset = 0
noise_dataset = "/media/administrator/736be68f-3ad2-4ea3-8ebf-c2e3983b05c9/Data/DNS-Challenge/datasets/noise"
noise_dataset_limit = false
noise_dataset_offset = 0
rir_dataset = "/media/administrator/736be68f-3ad2-4ea3-8ebf-c2e3983b05c9/Data/DNS-Challenge/datasets/impulse_responses"
rir_dataset_limit = false
rir_dataset_offset = 0
snr_range = [-5, 20]
reverb_proportion = 0.75
silence_length = 0.2
target_dB_FS = -25
target_dB_FS_floating_value = 10
sub_sample_length = 3.072
sr = 16000
pre_load_clean_dataset = false
pre_load_noise = false
pre_load_rir = false
num_workers = 36

[train_dataset.dataloader]
batch_size = 1
num_workers = 10
shuffle = true
pin_memory = true
drop_last = true

[validation_dataset]
path = "dataset.DNS_INTERSPEECH_validation.Dataset"
[validation_dataset.args]
#dataset_dir_list = "/home/administrator/Data/DNS-Challenge/dataset/raw_data/test_set/synthetic/no_reverb/audio/noisy"
dataset_dir_list = ["/home/administrator/Data/DNS-Challenge/datasets/test_set/synthetic/no_reverb/audio",
                    "/home/administrator/Data/DNS-Challenge/datasets/test_set/synthetic/with_reverb/audio"]
sr = 16000

[model]
path = "model.interaction_fullsubnet_model.Model"
[model.args]
n_freqs = 257
n_neighbor = 15
look_ahead = 2
num_sub_layers = 2
sequence_model = "LSTM"
fband_output_activate_function = "ReLU"
sband_output_activate_function = false
fband_model_hidden_size = 512
sband_model_hidden_size = 384
bidirectional = false
weight_init = true
#use_offline_laplace_norm = true
#use_offline_gaussian_norm = false
use_offline_norm = true
use_cumulative_norm = false
use_forgetting_norm = false
use_hybrid_norm = false
num_sub_batches = 3

[loss_function]
path = "model.loss.mse_loss"

[optimizer]
lr = 0.001
beta1 = 0.9
beta2 = 0.999

[trainer]
path = "trainer.fullsubnet_trainer.Trainer"
[trainer.train]
epochs = 9999
save_checkpoint_interval = 10
clip_grad_norm_value = 5
[trainer.validation]
validation_interval = 5
save_max_metric_score = true
[trainer.visualization]
n_samples = 10
num_workers = 36
metrics = ["WB_PESQ", "NB_PESQ", "STOI", "SI_SDR"]
